export const lightTheme = {
  mode: 'light',
  PRIMARY_BACKGROUND_COLOR: '#fff',
  SECONDARY_BACKGROUND_COLOR: '#fafafa',
  PRIMARY_TEXT_COLOR: 'rgba(0, 0, 0, 0.87)',
  SECONDARY_TEXT_COLOR: 'rgba(0, 0, 0, 0.54)',
  PRIMARY_BUTTON_COLOR: '#1976d2',
  SECONDARY_BUTTON_COLOR: '#64b5f6',
};
export const darkTheme = {
  mode: 'dark',
  PRIMARY_BACKGROUND_COLOR: '#303030',
  SECONDARY_BACKGROUND_COLOR: '#424242',
  PRIMARY_TEXT_COLOR: '#ffffff',
  SECONDARY_TEXT_COLOR: 'rgba(255, 255, 255, 0.7)',
  PRIMARY_BUTTON_COLOR: '#2196f3',
  SECONDARY_BUTTON_COLOR: '#64b5f6',
};
