export const lightTheme = {
  mode: 'light',
  PRIMARY_BACKGROUND_COLOR: '#ffffff',
  SECONDARY_BACKGROUND_COLOR: '#c4c4c4',
  PRIMARY_TEXT_COLOR: '#0E131F',
  SECONDARY_TEXT_COLOR: '#38405F',
  PRIMARY_BUTTON_COLOR: '#FF0035',
  SECONDARY_BUTTON_COLOR: '#C54A69',
};
export const darkTheme = {
  mode: 'dark',
  PRIMARY_BACKGROUND_COLOR: '#0E131F',
  SECONDARY_BACKGROUND_COLOR: '#c4c4c4',
  PRIMARY_TEXT_COLOR: '#ffffff',
  SECONDARY_TEXT_COLOR: '#999999',
  PRIMARY_BUTTON_COLOR: '#FF859D',
  SECONDARY_BUTTON_COLOR: '#520010',
};
